DROP TABLE IF EXISTS forecasts;

CREATE TABLE forecasts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    current_age INTEGER NOT NULL,
    net_income INTEGER NOT NULL,
    income_increase INTEGER NOT NULL,
    current_spending INTEGER NOT NULL,
    current_savings INTEGER NOT NULL,
    future_spending INTEGER NOT NULL,
    input_roi INTEGER NOT NULL,
    input_withdrawal_rate INTEGER NOT NULL
);