-- TRUNCATE all tables to ensure that there are no
-- data in them so we start with a fresh set of data
TRUNCATE forecasts, cards RESTART IDENTITY CASCADE;

-- insert 1 example forecast
INSERT INTO forecasts
  (current_age, net_income, income_increase, current_spending, current_savings, future_spending, input_roi, input_withdrawal_rate)
  VALUES
    ('30', '57000', '4', '60000', '100000', '60000', '8', '4');

-- insert 8 cards
INSERT INTO cards
  (title, content)
  VALUES
    ('Age of independence', 'I baby gluten-free wolf umami before they sold out letterpress. Drinking vinegar next level edison bulb, subway tile etsy sartorial hot chicken shaman bushwick. Cloud bread yr cray, tumblr tousled adaptogen helvetica hashtag chillwave put a bird on it. Cray williamsburg pabst, stumptown kombucha microdosing brooklyn gentrify scenester typewriter.'),
    ('A look into the future', 'Woke retro unicorn etsy, twee waistcoat celiac cliche freegan vinyl franzen green juice normcore. Raw denim cloud bread neutra, yr woke keffiyeh activated charcoal listicle thundercats. Ethical scenester raw denim deep v, dreamcatcher keffiyeh fanny pack distillery next level trust fund 8-bit snackwave brunch woke chartreuse. Sustainable tbh craft beer, pickled lumbersexual vexillologist copper mug marfa polaroid tumblr XOXO etsy swag pour-over. Air plant direct trade aesthetic, vegan messenger bag tumeric cray bitters blue bottle. Art party viral woke brooklyn tofu letterpress YOLO four loko.'),
    ('Where you are in your journey', 'Four dollar toast slow-carb woke roof party. DIY gentrify small batch banh mi kombucha, man braid affogato adaptogen keytar raclette shabby chic shaman keffiyeh chartreuse raw denim. Stumptown etsy disrupt, neutra chicharrones gluten-free thundercats yuccie. Seitan swag meditation humblebrag drinking vinegar. Pork belly drinking vinegar mixtape, crucifix hell of next level blog shoreditch air plant.'),
    ('Your nest egg', 'Hoodie pok pok tumeric narwhal ugh freegan. Biodiesel craft beer put a bird on it, post-ironic paleo sustainable asymmetrical typewriter gochujang godard intelligentsia celiac pitchfork before they sold out jianbing. Fam PBR&B humblebrag woke lo-fi la croix food truck iceland. Pour-over tbh bushwick distillery +1 90 squid hammock vaporware narwhal umami hell of. Jean shorts kale chips palo santo YOLO, four dollar toast swag kinfolk intelligentsia. 90 swag marfa plaid ramps, art party letterpress. Activated charcoal williamsburg organic live-edge yuccie sustainable health goth brunch venmo hot chicken bushwick fam everyday carry wolf.'),
    ('Here is how much you save per month', 'Four dollar toast brooklyn crucifix pok pok twee shabby chic. Paleo franzen locavore bicycle rights, helvetica meggings blue bottle affogato yuccie post-ironic messenger bag hexagon. Kitsch umami snackwave keffiyeh, humblebrag dreamcatcher cardigan sustainable XOXO schlitz yuccie everyday carry man braid. Try-hard 90s whatever, artisan yr PBR&B chillwave venmo raw denim organic echo park irony vape. Lyft kombucha lo-fi pabst leggings master cleanse. Humblebrag roof party YOLO vice prism tilde before they sold out pickled cronut freegan taxidermy. Af locavore chambray cred thundercats gochujang salvia keytar photo booth.'),
    ('How much you save can have a big impact on your net worth', 'Tofu wayfarers deep v literally hell of hexagon. Tofu hell of marfa portland hoodie prism. Flexitarian pinterest tilde occupy man braid. Tofu 3 wolf moon ethical, taxidermy blog small batch VHS tousled drinking vinegar mumblecore. Glossier air plant XOXO iceland. Normcore celiac green juice hot chicken fingerstache craft beer etsy distillery keytar sustainable cronut hammock small batch. Franzen kinfolk 90s freegan jianbing.'),
    ('Based on your net worth today, here is how much you could withdraw each year', 'Etsy cliche schlitz street art whatever four dollar toast pug asymmetrical edison bulb coloring book typewriter tumblr semiotics glossier biodiesel. Craft beer listicle schlitz franzen crucifix. Tumeric pop-up polaroid cloud bread roof party. Skateboard hexagon cred, cornhole aesthetic next level squid bitters la croix lomo asymmetrical ennui farm-to-table fashion axe selfies. Tumeric unicorn four loko shoreditch, next level kitsch stumptown synth.'),
    ('Based on your net worth today, here is how much you could withdraw each month', 'DIY pork belly kickstarter affogato sriracha celiac. DIY copper mug gochujang, letterpress schlitz fanny pack pitchfork asymmetrical chillwave. Succulents XOXO dreamcatcher la croix, mumblecore vaporware organic marfa cornhole. Four dollar toast pok pok 3 wolf moon waistcoat raclette locavore, master cleanse mixtape coloring book swag banh mi la croix hammock fixie gochujang. Quinoa health goth gluten-free street art.');